In [9]:
import pandas as pd


try:
    train_df = pd.read_csv('/content/train (4).csv')
    test_df = pd.read_csv('/content/test (3).csv')
    sample_submission_df = pd.read_csv('/content/sample_submission (4).csv')
    print("Datasets loaded successfully.")
except FileNotFoundError as e:
    print(f"Error loading file: {e}. Please ensure 'train.csv', 'test.csv', and 'sample_submission.csv' are in the correct directory.")
    train_df = None
    test_df = None
    sample_submission_df = None



if train_df is not None:
    print("\n--- Training Data Head ---")
    display(train_df.head())

    print("\n--- Training Data Info ---")
    train_df.info()

    print("\n--- Training Data Description ---")
    display(train_df.describe(include='all'))

if test_df is not None:
    print("\n--- Test Data Head ---")
    display(test_df.head())

if sample_submission_df is not None:
    print("\n--- Sample Submission Head ---")
    display(sample_submission_df.head())

Datasets loaded successfully.

--- Training Data Head ---

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,Male,0,Yes,Yes,29,Yes,No,DSL,Yes,...,Yes,Yes,No,No,One year,Yes,Mailed check,60.10,1653.85,No
1,1,Male,0,Yes,Yes,58,Yes,No,DSL,Yes,...,No,Yes,Yes,No,Two year,No,Credit card (automatic),69.50,3778.20,No
2,2,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,100.40,5841.35,No
3,3,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,69.70,70.70,Yes
4,4,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.45,70.45,Yes

--- Training Data Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594194 entries, 0 to 594193
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                594194 non-null  int64
 1   gender            594194 non-null  object
 2   SeniorCitizen     594194 non-null  int64
 3   Partner           594194 non-null  object
 4   Dependents        594194 non-null  object
 5   tenure            594194 non-null  int64
 6   PhoneService      594194 non-null  object
 7   MultipleLines     594194 non-null  object
 8   InternetService   594194 non-null  object
 9   OnlineSecurity    594194 non-null  object
 10  OnlineBackup      594194 non-null  object
 11  DeviceProtection  594194 non-null  object
 12  TechSupport       594194 non-null  object
 13  StreamingTV       594194 non-null  object
 14  StreamingMovies   594194 non-null  object
 15  Contract          594194 non-null  object
 16  PaperlessBilling  594194 non-null  object
 17  PaymentMethod     594194 non-null  object
 18  MonthlyCharges    594194 non-null  float64
 19  TotalCharges      594194 non-null  float64
 20  Churn             594194 non-null  object
dtypes: float64(2), int64(3), object(16)
memory usage: 95.2+ MB

--- Training Data Description ---

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
count,594194.000000,594194,594194.000000,594194,594194,594194.000000,594194,594194,594194,594194,...,594194,594194,594194,594194,594194,594194,594194,594194.000000,594194.000000,594194
unique,NaN,2,NaN,2,2,NaN,2,3,3,3,...,3,3,3,3,3,2,4,NaN,NaN,2
top,NaN,Female,NaN,Yes,No,NaN,Yes,No,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,NaN,NaN,No
freq,NaN,298738,NaN,309554,414362,NaN,557893,283384,272386,289474,...,247377,288571,240301,241435,298918,365579,215372,NaN,NaN,460377
mean,297096.500000,NaN,0.114102,NaN,NaN,36.577258,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.866223,2494.377057,NaN
std,171529.177262,NaN,0.317936,NaN,NaN,25.061922,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.067444,2353.916710,NaN
min,0.000000,NaN,0.000000,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.250000,18.800000,NaN
25%,148548.250000,NaN,0.000000,NaN,NaN,12.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.900000,639.650000,NaN
50%,297096.500000,NaN,0.000000,NaN,NaN,35.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.100000,1433.650000,NaN
75%,445644.750000,NaN,0.000000,NaN,NaN,62.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.800000,4263.800000,NaN
max,594193.000000,NaN,1.000000,NaN,NaN,72.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.750000,8684.800000,NaN

--- Test Data Head ---

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,594194,Female,0,Yes,No,72,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,115.55,8061.50
1,594195,Female,0,Yes,No,71,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),19.80,1336.50
2,594196,Male,0,No,No,12,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),55.55,633.55
3,594197,Male,0,Yes,Yes,71,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,Two year,No,Credit card (automatic),84.10,6457.15
4,594198,Female,0,No,No,15,Yes,No,Fiber optic,Yes,No,No,No,Yes,Yes,Month-to-month,No,Electronic check,90.35,1233.65

--- Sample Submission Head ---

       id  Churn
0  594194      0
1  594195      0
2  594196      0
3  594197      0
4  594198      0

In [10]:
import numpy as np

# --- Preprocessing for train_df ---
print("\n--- Preprocessing Training Data ---")

if 'TotalCharges' in train_df.columns:

    train_df['TotalCharges_temp'] = pd.to_numeric(train_df['TotalCharges'], errors='coerce')

    if train_df['TotalCharges_temp'].isnull().any():
        print("Found non-numeric values in 'TotalCharges' (training data). Converting to numeric and handling NaNs.")
        train_df['TotalCharges'] = pd.to_numeric(train_df['TotalCharges'], errors='coerce')
        train_df['TotalCharges'].fillna(train_df['TotalCharges'].median(), inplace=True)
    else:
        print("No explicit non-numeric values found in 'TotalCharges' (training data). Converting if not already numeric.")
        train_df['TotalCharges'] = train_df['TotalCharges_temp']
    train_df.drop(columns=['TotalCharges_temp'], inplace=True)
else:
    print("TotalCharges column not found in training data.")

train_df['Churn'] = train_df['Churn'].map({'No': 0, 'Yes': 1})

print("\nUnique values for object columns in training data:")
for column in train_df.select_dtypes(include='object').columns:
    print(f"{column}: {train_df[column].unique()}")

print("\n--- Preprocessing Test Data ---")

if 'TotalCharges' in test_df.columns:
    test_df['TotalCharges_temp'] = pd.to_numeric(test_df['TotalCharges'], errors='coerce')
    if test_df['TotalCharges_temp'].isnull().any():
        print("Found non-numeric values in 'TotalCharges' (test data). Converting to numeric and handling NaNs.")
        test_df['TotalCharges'] = pd.to_numeric(test_df['TotalCharges'], errors='coerce')

        if train_df is not None and 'TotalCharges' in train_df.columns:
            test_df['TotalCharges'].fillna(train_df['TotalCharges'].median(), inplace=True)
        else:
            test_df['TotalCharges'].fillna(test_df['TotalCharges'].median(), inplace=True) # Fallback if train_df not available
    else:
        print("No explicit non-numeric values found in 'TotalCharges' (test data). Converting if not already numeric.")
        test_df['TotalCharges'] = test_df['TotalCharges_temp']
    test_df.drop(columns=['TotalCharges_temp'], inplace=True)
else:
    print("TotalCharges column not found in test data.")

print("\nUnique values for object columns in test data:")
for column in test_df.select_dtypes(include='object').columns:
    print(f"{column}: {test_df[column].unique()}")

print("\n--- Training Data Info After Preprocessing ---")
train_df.info()
print("\n--- Test Data Info After Preprocessing ---")
test_df.info()

--- Preprocessing Training Data ---
No explicit non-numeric values found in 'TotalCharges' (training data). Converting if not already numeric.

Unique values for object columns in training data:
gender: ['Male' 'Female']
Partner: ['Yes' 'No']
Dependents: ['Yes' 'No']
PhoneService: ['Yes' 'No']
MultipleLines: ['No' 'Yes' 'No phone service']
InternetService: ['DSL' 'Fiber optic' 'No']
OnlineSecurity: ['Yes' 'No' 'No internet service']
OnlineBackup: ['No' 'Yes' 'No internet service']
DeviceProtection: ['Yes' 'No' 'No internet service']
TechSupport: ['Yes' 'No' 'No internet service']
StreamingTV: ['No' 'Yes' 'No internet service']
StreamingMovies: ['No' 'Yes' 'No internet service']
Contract: ['One year' 'Two year' 'Month-to-month']
PaperlessBilling: ['Yes' 'No']
PaymentMethod: ['Mailed check' 'Credit card (automatic)' 'Electronic check'
 'Bank transfer (automatic)']

--- Preprocessing Test Data ---
No explicit non-numeric values found in 'TotalCharges' (test data). Converting if not already numeric.

Unique values for object columns in test data:
gender: ['Female' 'Male']
Partner: ['Yes' 'No']
Dependents: ['No' 'Yes']
PhoneService: ['Yes' 'No']
MultipleLines: ['Yes' 'No' 'No phone service']
InternetService: ['Fiber optic' 'No' 'DSL']
OnlineSecurity: ['Yes' 'No internet service' 'No']
OnlineBackup: ['Yes' 'No internet service' 'No']
DeviceProtection: ['Yes' 'No internet service' 'No']
TechSupport: ['Yes' 'No internet service' 'No']
StreamingTV: ['Yes' 'No internet service' 'No']
StreamingMovies: ['Yes' 'No internet service' 'No']
Contract: ['Two year' 'Month-to-month' 'One year']
PaperlessBilling: ['Yes' 'No']
PaymentMethod: ['Electronic check' 'Bank transfer (automatic)' 'Credit card (automatic)'
 'Mailed check']

--- Training Data Info After Preprocessing ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594194 entries, 0 to 594193
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                594194 non-null  int64
 1   gender            594194 non-null  object
 2   SeniorCitizen     594194 non-null  int64
 3   Partner           594194 non-null  object
 4   Dependents        594194 non-null  object
 5   tenure            594194 non-null  int64
 6   PhoneService      594194 non-null  object
 7   MultipleLines     594194 non-null  object
 8   InternetService   594194 non-null  object
 9   OnlineSecurity    594194 non-null  object
 10  OnlineBackup      594194 non-null  object
 11  DeviceProtection  594194 non-null  object
 12  TechSupport       594194 non-null  object
 13  StreamingTV       594194 non-null  object
 14  StreamingMovies   594194 non-null  object
 15  Contract          594194 non-null  object
 16  PaperlessBilling  594194 non-null  object
 17  PaymentMethod     594194 non-null  object
 18  MonthlyCharges    594194 non-null  float64
 19  TotalCharges      594194 non-null  float64
 20  Churn             594194 non-null  int64
dtypes: float64(2), int64(4), object(15)
memory usage: 95.2+ MB

--- Test Data Info After Preprocessing ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254655 entries, 0 to 254654
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                254655 non-null  int64
 1   gender            254655 non-null  object
 2   SeniorCitizen     254655 non-null  int64
 3   Partner           254655 non-null  object
 4   Dependents        254655 non-null  object
 5   tenure            254655 non-null  int64
 6   PhoneService      254655 non-null  object
 7   MultipleLines     254655 non-null  object
 8   InternetService   254655 non-null  object
 9   OnlineSecurity    254655 non-null  object
 10  OnlineBackup      254655 non-null  object
 11  DeviceProtection  254655 non-null  object
 12  TechSupport       254655 non-null  object
 13  StreamingTV       254655 non-null  object
 14  StreamingMovies   254655 non-null  object
 15  Contract          254655 non-null  object
 16  PaperlessBilling  254655 non-null  object
 17  PaymentMethod     254655 non-null  object
 18  MonthlyCharges    254655 non-null  float64
 19  TotalCharges      254655 non-null  float64
dtypes: float64(2), int64(3), object(15)
memory usage: 38.9+ MB

In [11]:
print("\n--- Feature Engineering and Encoding Categorical Variables ---")

categorical_cols_train = train_df.select_dtypes(include='object').columns
categorical_cols_test = test_df.select_dtypes(include='object').columns

train_ids = train_df['id']
test_ids = test_df['id']
train_df = train_df.drop('id', axis=1)
test_df = test_df.drop('id', axis=1)


internet_service_cols = ['OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies']
phone_service_col = ['MultipleLines']

for col in internet_service_cols:
    if col in train_df.columns:
        train_df[col] = train_df[col].replace('No internet service', 'No')
    if col in test_df.columns:
        test_df[col] = test_df[col].replace('No internet service', 'No')

for col in phone_service_col:
    if col in train_df.columns:
        train_df[col] = train_df[col].replace('No phone service', 'No')
    if col in test_df.columns:
        test_df[col] = test_df[col].replace('No phone service', 'No')


train_df_encoded = pd.get_dummies(train_df, columns=categorical_cols_train, drop_first=False)
test_df_encoded = pd.get_dummies(test_df, columns=categorical_cols_test, drop_first=False)

common_cols = list(set(train_df_encoded.columns) & set(test_df_encoded.columns))
train_df_encoded = train_df_encoded[common_cols + ['Churn']]
test_df_encoded = test_df_encoded[common_cols]

missing_in_test = set(train_df_encoded.columns) - set(test_df_encoded.columns) - {'Churn'}
for col in missing_in_test:
    test_df_encoded[col] = 0

missing_in_train = set(test_df_encoded.columns) - set(train_df_encoded.columns)
for col in missing_in_train:
    train_df_encoded[col] = 0

test_df_encoded = test_df_encoded[train_df_encoded.drop(columns='Churn').columns]

print("--- DataFrames after One-Hot Encoding ---")
print("Train DataFrame Head:")
display(train_df_encoded.head())
print("Test DataFrame Head:")
display(test_df_encoded.head())

print("Train DataFrame Info after encoding:")
train_df_encoded.info()
print("Test DataFrame Info after encoding:")
test_df_encoded.info()

print("\n--- Churn Distribution in Training Data ---")
churn_counts = train_df_encoded['Churn'].value_counts()
print(churn_counts)
print(f"Churn percentage: {churn_counts[1] / churn_counts.sum() * 100:.2f}%")
print(f"No Churn percentage: {churn_counts[0] / churn_counts.sum() * 100:.2f}%")

--- Feature Engineering and Encoding Categorical Variables ---
--- DataFrames after One-Hot Encoding ---
Train DataFrame Head:

,tenure,Contract_One year,OnlineSecurity_No,PaymentMethod_Electronic check,MonthlyCharges,OnlineSecurity_Yes,TechSupport_Yes,Contract_Two year,InternetService_DSL,PhoneService_Yes,...,MultipleLines_Yes,TechSupport_No,StreamingMovies_No,DeviceProtection_Yes,OnlineBackup_No,Dependents_No,DeviceProtection_No,Contract_Month-to-month,Dependents_Yes,Churn
0,29,True,False,False,60.10,True,True,False,True,True,...,False,False,True,True,True,False,False,False,True,0
1,58,False,False,False,69.50,True,True,True,True,True,...,False,False,True,False,False,False,True,False,True,0
2,58,False,True,True,100.40,False,False,False,False,True,...,True,True,False,False,False,True,True,True,False,0
3,1,False,True,True,69.70,False,False,False,False,True,...,False,True,True,False,True,True,True,True,False,1
4,1,False,True,True,70.45,False,False,False,False,True,...,False,True,True,False,True,True,True,True,False,1

Test DataFrame Head:

,tenure,Contract_One year,OnlineSecurity_No,PaymentMethod_Electronic check,MonthlyCharges,OnlineSecurity_Yes,TechSupport_Yes,Contract_Two year,InternetService_DSL,PhoneService_Yes,...,Partner_Yes,MultipleLines_Yes,TechSupport_No,StreamingMovies_No,DeviceProtection_Yes,OnlineBackup_No,Dependents_No,DeviceProtection_No,Contract_Month-to-month,Dependents_Yes
0,72,False,False,True,115.55,True,True,True,False,True,...,True,True,False,False,True,False,True,False,False,False
1,71,False,True,False,19.80,False,False,True,False,True,...,True,False,True,True,False,True,True,True,False,False
2,12,False,False,False,55.55,True,False,False,True,True,...,False,False,True,True,False,False,True,True,True,False
3,71,False,False,False,84.10,True,True,True,True,True,...,True,True,False,False,True,True,False,False,False,True
4,15,False,False,True,90.35,True,False,False,False,True,...,False,False,True,False,False,True,True,True,True,False

Train DataFrame Info after encoding:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594194 entries, 0 to 594193
Data columns (total 39 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   tenure                                   594194 non-null  int64
 1   Contract_One year                        594194 non-null  bool
 2   OnlineSecurity_No                        594194 non-null  bool
 3   PaymentMethod_Electronic check           594194 non-null  bool
 4   MonthlyCharges                           594194 non-null  float64
 5   OnlineSecurity_Yes                       594194 non-null  bool
 6   TechSupport_Yes                          594194 non-null  bool
 7   Contract_Two year                        594194 non-null  bool
 8   InternetService_DSL                      594194 non-null  bool
 9   PhoneService_Yes                         594194 non-null  bool
 10  InternetService_No                       594194 non-null  bool
 11  TotalCharges                             594194 non-null  float64
 12  MultipleLines_No                         594194 non-null  bool
 13  gender_Female                            594194 non-null  bool
 14  StreamingMovies_Yes                      594194 non-null  bool
 15  PaperlessBilling_No                      594194 non-null  bool
 16  OnlineBackup_Yes                         594194 non-null  bool
 17  InternetService_Fiber optic              594194 non-null  bool
 18  PaymentMethod_Credit card (automatic)    594194 non-null  bool
 19  StreamingTV_No                           594194 non-null  bool
 20  PaperlessBilling_Yes                     594194 non-null  bool
 21  PaymentMethod_Bank transfer (automatic)  594194 non-null  bool
 22  PaymentMethod_Mailed check               594194 non-null  bool
 23  Partner_No                               594194 non-null  bool
 24  gender_Male                              594194 non-null  bool
 25  PhoneService_No                          594194 non-null  bool
 26  StreamingTV_Yes                          594194 non-null  bool
 27  SeniorCitizen                            594194 non-null  int64
 28  Partner_Yes                              594194 non-null  bool
 29  MultipleLines_Yes                        594194 non-null  bool
 30  TechSupport_No                           594194 non-null  bool
 31  StreamingMovies_No                       594194 non-null  bool
 32  DeviceProtection_Yes                     594194 non-null  bool
 33  OnlineBackup_No                          594194 non-null  bool
 34  Dependents_No                            594194 non-null  bool
 35  DeviceProtection_No                      594194 non-null  bool
 36  Contract_Month-to-month                  594194 non-null  bool
 37  Dependents_Yes                           594194 non-null  bool
 38  Churn                                    594194 non-null  int64
dtypes: bool(34), float64(2), int64(3)
memory usage: 41.9 MB
Test DataFrame Info after encoding:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254655 entries, 0 to 254654
Data columns (total 38 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   tenure                                   254655 non-null  int64
 1   Contract_One year                        254655 non-null  bool
 2   OnlineSecurity_No                        254655 non-null  bool
 3   PaymentMethod_Electronic check           254655 non-null  bool
 4   MonthlyCharges                           254655 non-null  float64
 5   OnlineSecurity_Yes                       254655 non-null  bool
 6   TechSupport_Yes                          254655 non-null  bool
 7   Contract_Two year                        254655 non-null  bool
 8   InternetService_DSL                      254655 non-null  bool
 9   PhoneService_Yes                         254655 non-null  bool
 10  InternetService_No                       254655 non-null  bool
 11  TotalCharges                             254655 non-null  float64
 12  MultipleLines_No                         254655 non-null  bool
 13  gender_Female                            254655 non-null  bool
 14  StreamingMovies_Yes                      254655 non-null  bool
 15  PaperlessBilling_No                      254655 non-null  bool
 16  OnlineBackup_Yes                         254655 non-null  bool
 17  InternetService_Fiber optic              254655 non-null  bool
 18  PaymentMethod_Credit card (automatic)    254655 non-null  bool
 19  StreamingTV_No                           254655 non-null  bool
 20  PaperlessBilling_Yes                     254655 non-null  bool
 21  PaymentMethod_Bank transfer (automatic)  254655 non-null  bool
 22  PaymentMethod_Mailed check               254655 non-null  bool
 23  Partner_No                               254655 non-null  bool
 24  gender_Male                              254655 non-null  bool
 25  PhoneService_No                          254655 non-null  bool
 26  StreamingTV_Yes                          254655 non-null  bool
 27  SeniorCitizen                            254655 non-null  int64
 28  Partner_Yes                              254655 non-null  bool
 29  MultipleLines_Yes                        254655 non-null  bool
 30  TechSupport_No                           254655 non-null  bool
 31  StreamingMovies_No                       254655 non-null  bool
 32  DeviceProtection_Yes                     254655 non-null  bool
 33  OnlineBackup_No                          254655 non-null  bool
 34  Dependents_No                            254655 non-null  bool
 35  DeviceProtection_No                      254655 non-null  bool
 36  Contract_Month-to-month                  254655 non-null  bool
 37  Dependents_Yes                           254655 non-null  bool
dtypes: bool(34), float64(2), int64(2)
memory usage: 16.0 MB

--- Churn Distribution in Training Data ---
Churn
0    460377
1    133817
Name: count, dtype: int64
Churn percentage: 22.52%
No Churn percentage: 77.48%

In [12]:
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

print("\n--- Splitting Data and Handling Imbalance (SMOTE) ---")

X = train_df_encoded.drop('Churn', axis=1)
y = train_df_encoded['Churn']

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"Original training set shape: X_train {X_train.shape}, y_train {y_train.shape}")
print(f"Original validation set shape: X_val {X_val.shape}, y_val {y_val.shape}")

print("\nOriginal training set class distribution:")
print(y_train.value_counts(normalize=True))

smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

print(f"\nResampled training set shape: X_train_resampled {X_train_resampled.shape}, y_train_resampled {y_train_resampled.shape}")
print("Resampled training set class distribution:")
print(y_train_resampled.value_counts(normalize=True))

print("\nValidation set class distribution (should be similar to original):")
print(y_val.value_counts(normalize=True))

--- Splitting Data and Handling Imbalance (SMOTE) ---
Original training set shape: X_train (475355, 38), y_train (475355,)
Original validation set shape: X_val (118839, 38), y_val (118839,)

Original training set class distribution:
Churn
0    0.774791
1    0.225209
Name: proportion, dtype: float64

Resampled training set shape: X_train_resampled (736602, 38), y_train_resampled (736602,)
Resampled training set class distribution:
Churn
0    0.5
1    0.5
Name: proportion, dtype: float64

Validation set class distribution (should be similar to original):
Churn
0    0.774796
1    0.225204
Name: proportion, dtype: float64

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix

print("\n--- Training Logistic Regression Model ---")

logistic_model = LogisticRegression(random_state=42, solver='liblinear', max_iter=1000)
logistic_model.fit(X_train_resampled, y_train_resampled)

print("Logistic Regression Model trained successfully.")

print("\n--- Evaluating Model Performance on Validation Set ---")

y_pred_val = logistic_model.predict(X_val)
y_pred_proba_val = logistic_model.predict_proba(X_val)[:, 1]

accuracy = accuracy_score(y_val, y_pred_val)
precision = precision_score(y_val, y_pred_val)
recall = recall_score(y_val, y_pred_val)
f1 = f1_score(y_val, y_pred_val)
roc_auc = roc_auc_score(y_val, y_pred_proba_val)
conf_matrix = confusion_matrix(y_val, y_pred_val)

print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")
print(f"ROC-AUC Score: {roc_auc:.4f}")
print("Confusion Matrix:")
print(conf_matrix)

print("\nInterpretation of Confusion Matrix:")
print("[[True Negative (TN), False Positive (FP)]")
print(" [False Negative (FN), True Positive (TP)]]")

--- Training Logistic Regression Model ---
Logistic Regression Model trained successfully.

--- Evaluating Model Performance on Validation Set ---
Accuracy: 0.8380
Precision: 0.6105
Recall: 0.7757
F1-Score: 0.6833
ROC-AUC Score: 0.9034
Confusion Matrix:
[[78834 13242]
 [ 6004 20759]]

Interpretation of Confusion Matrix:
[[True Negative (TN), False Positive (FP)]
 [False Negative (FN), True Positive (TP)]]

In [14]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
import numpy as np

print("\n--- Training RandomForestClassifier with Stratified K-Fold Cross-Validation ---")

rf_model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

accuracy_scores = []
precision_scores = []
recall_scores = []
f1_scores = []
roc_auc_scores = []

for fold, (train_index, val_index) in enumerate(skf.split(X_train_resampled, y_train_resampled)):
    print(f"\n--- Fold {fold+1}/{skf.n_splits} ---")
    X_train_fold, X_val_fold = X_train_resampled.iloc[train_index], X_train_resampled.iloc[val_index]
    y_train_fold, y_val_fold = y_train_resampled.iloc[train_index], y_train_resampled.iloc[val_index]

    rf_model.fit(X_train_fold, y_train_fold)

    y_pred_fold = rf_model.predict(X_val_fold)
    y_pred_proba_fold = rf_model.predict_proba(X_val_fold)[:, 1]

    accuracy_scores.append(accuracy_score(y_val_fold, y_pred_fold))
    precision_scores.append(precision_score(y_val_fold, y_pred_fold))
    recall_scores.append(recall_score(y_val_fold, y_pred_fold))
    f1_scores.append(f1_score(y_val_fold, y_pred_fold))
    roc_auc_scores.append(roc_auc_score(y_val_fold, y_pred_proba_fold))

    print(f"Fold {fold+1} Accuracy: {accuracy_scores[-1]:.4f}")
    print(f"Fold {fold+1} Precision: {precision_scores[-1]:.4f}")
    print(f"Fold {fold+1} Recall: {recall_scores[-1]:.4f}")
    print(f"Fold {fold+1} F1-Score: {f1_scores[-1]:.4f}")
    print(f"Fold {fold+1} ROC-AUC: {roc_auc_scores[-1]:.4f}")

print("\n--- Cross-Validation Results (Mean and Standard Deviation) ---")
print(f"Mean Accuracy: {np.mean(accuracy_scores):.4f} (+/- {np.std(accuracy_scores):.4f})")
print(f"Mean Precision: {np.mean(precision_scores):.4f} (+/- {np.std(precision_scores):.4f})")
print(f"Mean Recall: {np.mean(recall_scores):.4f} (+/- {np.std(recall_scores):.4f})")
print(f"Mean F1-Score: {np.mean(f1_scores):.4f} (+/- {np.std(f1_scores):.4f})")
print(f"Mean ROC-AUC: {np.mean(roc_auc_scores):.4f} (+/- {np.std(roc_auc_scores):.4f})")

print("\n--- Training Final RandomForest Model on full resampled training data ---")
final_rf_model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
final_rf_model.fit(X_train_resampled, y_train_resampled)
print("Final RandomForest Model trained successfully.")

print("\n--- Evaluating Final RandomForest Model on Independent Validation Set ---")
y_pred_final_val = final_rf_model.predict(X_val)
y_pred_proba_final_val = final_rf_model.predict_proba(X_val)[:, 1]

accuracy_final = accuracy_score(y_val, y_pred_final_val)
precision_final = precision_score(y_val, y_pred_final_val)
recall_final = recall_score(y_val, y_pred_final_val)
f1_final = f1_score(y_val, y_pred_final_val)
roc_auc_final = roc_auc_score(y_val, y_pred_proba_final_val)

print(f"Final Model Accuracy on Validation Set: {accuracy_final:.4f}")
print(f"Final Model Precision on Validation Set: {precision_final:.4f}")
print(f"Final Model Recall on Validation Set: {recall_final:.4f}")
print(f"Final Model F1-Score on Validation Set: {f1_final:.4f}")
print(f"Final Model ROC-AUC on Validation Set: {roc_auc_final:.4f}")

--- Training RandomForestClassifier with Stratified K-Fold Cross-Validation ---

--- Fold 1/5 ---
Fold 1 Accuracy: 0.8991
Fold 1 Precision: 0.9028
Fold 1 Recall: 0.8944
Fold 1 F1-Score: 0.8986
Fold 1 ROC-AUC: 0.9652

--- Fold 2/5 ---
Fold 2 Accuracy: 0.8987
Fold 2 Precision: 0.9021
Fold 2 Recall: 0.8945
Fold 2 F1-Score: 0.8982
Fold 2 ROC-AUC: 0.9654

--- Fold 3/5 ---
Fold 3 Accuracy: 0.9000
Fold 3 Precision: 0.9010
Fold 3 Recall: 0.8988
Fold 3 F1-Score: 0.8999
Fold 3 ROC-AUC: 0.9662

--- Fold 4/5 ---
Fold 4 Accuracy: 0.8991
Fold 4 Precision: 0.9023
Fold 4 Recall: 0.8951
Fold 4 F1-Score: 0.8987
Fold 4 ROC-AUC: 0.9652

--- Fold 5/5 ---
Fold 5 Accuracy: 0.8995
Fold 5 Precision: 0.9017
Fold 5 Recall: 0.8967
Fold 5 F1-Score: 0.8992
Fold 5 ROC-AUC: 0.9657

--- Cross-Validation Results (Mean and Standard Deviation) ---
Mean Accuracy: 0.8993 (+/- 0.0004)
Mean Precision: 0.9020 (+/- 0.0006)
Mean Recall: 0.8959 (+/- 0.0017)
Mean F1-Score: 0.8989 (+/- 0.0006)
Mean ROC-AUC: 0.9655 (+/- 0.0004)

--- Training Final RandomForest Model on full resampled training data ---
Final RandomForest Model trained successfully.

--- Evaluating Final RandomForest Model on Independent Validation Set ---
Final Model Accuracy on Validation Set: 0.8413
Final Model Precision on Validation Set: 0.6532
Final Model Recall on Validation Set: 0.6298
Final Model F1-Score on Validation Set: 0.6413
Final Model ROC-AUC on Validation Set: 0.8924

In [15]:
import xgboost as xgb
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint, uniform
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix

print("\n--- Performing Hyperparameter Tuning for XGBoost Classifier ---")

param_dist_xgb = {
    'n_estimators': randint(100, 500),
    'learning_rate': uniform(0.01, 0.3),
    'max_depth': randint(3, 10),
    'subsample': uniform(0.6, 0.4),
    'colsample_bytree': uniform(0.6, 0.4),
    'gamma': uniform(0, 0.5),
    'lambda': uniform(1, 10),
    'alpha': uniform(0, 5),
    'objective': ['binary:logistic'],
    'eval_metric': ['logloss']
}

random_search_xgb = RandomizedSearchCV(
    estimator=xgb.XGBClassifier(random_state=42, use_label_encoder=False, n_jobs=-1, tree_method='hist'),
    param_distributions=param_dist_xgb,
    n_iter=30,
    cv=3,
    verbose=1,
    random_state=42,
    n_jobs=-1,
    scoring='roc_auc'
)

random_search_xgb.fit(X_train_resampled, y_train_resampled)

print("\nBest parameters found by RandomizedSearchCV for XGBoost:")
print(random_search_xgb.best_params_)
print("\nBest ROC-AUC score found by RandomizedSearchCV for XGBoost (on cross-validation folds):")
print(f"{random_search_xgb.best_score_:.4f}")

best_xgb_model = random_search_xgb.best_estimator_

print("\n--- Evaluating Tuned XGBoost Model on Independent Validation Set ---")

y_pred_tuned_xgb_val = best_xgb_model.predict(X_val)
y_pred_proba_tuned_xgb_val = best_xgb_model.predict_proba(X_val)[:, 1]

accuracy_tuned_xgb = accuracy_score(y_val, y_pred_tuned_xgb_val)
precision_tuned_xgb = precision_score(y_val, y_pred_tuned_xgb_val)
recall_tuned_xgb = recall_score(y_val, y_pred_tuned_xgb_val)
f1_tuned_xgb = f1_score(y_val, y_pred_tuned_xgb_val)
roc_auc_tuned_xgb = roc_auc_score(y_val, y_pred_proba_tuned_xgb_val)
conf_matrix_tuned_xgb = confusion_matrix(y_val, y_pred_tuned_xgb_val)

print(f"Tuned XGBoost Model Accuracy on Validation Set: {accuracy_tuned_xgb:.4f}")
print(f"Tuned XGBoost Model Precision on Validation Set: {precision_tuned_xgb:.4f}")
print(f"Tuned XGBoost Model Recall on Validation Set: {recall_tuned_xgb:.4f}")
print(f"Tuned XGBoost Model F1-Score on Validation Set: {f1_tuned_xgb:.4f}")
print(f"Tuned XGBoost Model ROC-AUC on Validation Set: {roc_auc_tuned_xgb:.4f}")
print("Confusion Matrix for Tuned XGBoost Model:")
print(conf_matrix_tuned_xgb)

--- Performing Hyperparameter Tuning for XGBoost Classifier ---
Fitting 3 folds for each of 30 candidates, totalling 90 fits

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [18:29:36] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Best parameters found by RandomizedSearchCV for XGBoost:
{'alpha': np.float64(1.3606612469231765), 'colsample_bytree': np.float64(0.8590760482165449), 'eval_metric': 'logloss', 'gamma': np.float64(0.0002601884976579094), 'lambda': np.float64(4.52568856334169), 'learning_rate': np.float64(0.1014343774474087), 'max_depth': 8, 'n_estimators': 236, 'objective': 'binary:logistic', 'subsample': np.float64(0.7939319885435933)}

Best ROC-AUC score found by RandomizedSearchCV for XGBoost (on cross-validation folds):
0.9639

--- Evaluating Tuned XGBoost Model on Independent Validation Set ---
Tuned XGBoost Model Accuracy on Validation Set: 0.8567
Tuned XGBoost Model Precision on Validation Set: 0.6762
Tuned XGBoost Model Recall on Validation Set: 0.6976
Tuned XGBoost Model F1-Score on Validation Set: 0.6867
Tuned XGBoost Model ROC-AUC on Validation Set: 0.9141
Confusion Matrix for Tuned XGBoost Model:
[[83136  8940]
 [ 8094 18669]]

In [16]:
print("\n--- Generating Submission Files ---")

xgb_test_predictions = best_xgb_model.predict(test_df_encoded)

xgb_submission_df = pd.DataFrame({'id': test_ids, 'Churn': xgb_test_predictions})

xgb_submission_filename = 'submission_xgboost.csv'
xgb_submission_df.to_csv(xgb_submission_filename, index=False)
print(f"XGBoost submission file '{xgb_submission_filename}' created successfully.")

rf_test_predictions = final_rf_model.predict(test_df_encoded)

rf_submission_df = pd.DataFrame({'id': test_ids, 'Churn': rf_test_predictions})

rf_submission_filename = 'submission_random_forest.csv'
rf_submission_df.to_csv(rf_submission_filename, index=False)
print(f"Random Forest submission file '{rf_submission_filename}' created successfully.")

logistic_test_predictions = logistic_model.predict(test_df_encoded)

logistic_submission_df = pd.DataFrame({'id': test_ids, 'Churn': logistic_test_predictions})

logistic_submission_filename = 'submission_logistic_regression.csv'
logistic_submission_df.to_csv(logistic_submission_filename, index=False)
print(f"Logistic Regression submission file '{logistic_submission_filename}' created successfully.")

print("\nSubmission files generated.")

--- Generating Submission Files ---
XGBoost submission file 'submission_xgboost.csv' created successfully.
Random Forest submission file 'submission_random_forest.csv' created successfully.
Logistic Regression submission file 'submission_logistic_regression.csv' created successfully.

Submission files generated.